version: "3"

services:
  ares-db:
    image: mariadb:10.4
    restart: unless-stopped
    container_name: ares-db
    volumes:
      - ares-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ares
      MYSQL_DATABASE: ares
    ports:
      - "3306:3306"
  ares-service:
    image: ghcr.io/newbies-workplace/ares:latest
    restart: unless-stopped
    container_name: ares-service
    environment:
      - ARES_DB_URL=jdbc:mariadb://ares-db:3306/ares?characterEncoding=utf8&useUnicode=true
      - ARES_DB_USERNAME=root
      - ARES_DB_PASSWORD=ares
      - OAUTH_GITHUB_CLIENT_ID
      - OAUTH_GITHUB_SECRET
      - JWT_GENERATOR_SIGNATURE_SECRET
    ports:
      - "8080:8080"
    depends_on:
      - ares-db
volumes:
  ares-db: