name: Feature CI

on:
  push:
    branches:
      - '**'

jobs:
  unit-test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Gradle cache
        uses: actions/cache@v3.0.8
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - name: Gradle test
        run: bash ./gradlew test

      - name: Tests results
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: ares/build/reports
